# This is a basic workflow to help you get started with Actions

name: Lambda CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: 
      - develop
      - master
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Installs Python
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    # Installs PIP
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt --target .
    # Install serverless and dependencies
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    # Configures AWS credentials from github secrets
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Deploy Dev
      if: github.ref == 'refs/heads/develop'
      uses: serverless/github-action@v2
      with:
        args: -c "serverless deploy --stage dev"
        entrypoint: /bin/sh
    - name: Deploy Prod
      if: github.ref == 'refs/heads/master'
      uses: serverless/github-action@v2
      with:
        args: -c "serverless deploy --stage prod" 
        entrypoint: /bin/sh
